# job that runs kiweeteam/shopware-e2e image to run e2e tests
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: e2e
          image: kiweeteam/shopware-e2e
          # include shopware config for the e2e tests
          envFrom:
            - configMapRef:
                name: shopware-app-config
            - secretRef:
                name: shopware-app-config
      restartPolicy: Never
