monolog:
  handlers:
    main:
      type: fingers_crossed
      excluded_http_codes: [404, 405]
      action_level: error
      handler: nested
    nested:
      type: stream
      path: "php://stderr"
      level: error
    console:
      type:   console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
