# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: shopware-kube
build:
  artifacts:
      - image: kiweeteam/franken-shopware
        docker:
          dockerfile: Dockerfile
          target: app-prod
          cacheFrom:
            - kiweeteam/franken-shopware
          buildArgs:
            BUILDKIT_INLINE_CACHE: "1"
          secrets:
            - id: composer_auth
              src: auth.json
      - image: kiweeteam/franken-shopware-dev
        sync:
          manual:
            - src: "custom/"
              dest: "/app/custom"
        docker:
          dockerfile: Dockerfile
          cacheFrom:
            - kiweeteam/franken-shopware-dev
          buildArgs:
            BUILDKIT_INLINE_CACHE: "1"
          target: app-dev
          secrets:
            - id: composer_auth
              src: auth.json
      - image: kiweeteam/shopware-e2e
        docker:
          dockerfile: e2e.Dockerfile
  local:
    useBuildkit: true
    concurrency: 3
manifests:
  kustomize:
    paths:
      - deploy/overlays/dev
deploy:
  statusCheck: true
  # fail deployment if it doesn't stabilize within 20 minutes.
  statusCheckDeadlineSeconds: 1200
  kubectl:
    defaultNamespace: shopware
  helm:
    # Install all required operators
    releases:
      - name: kubernetes-secret-generator
        repo: https://helm.mittwald.de
        remoteChart: kubernetes-secret-generator
        namespace: secret-generator
        createNamespace: true
        wait: true
        version: 3.4.0
        setValues:
          image:
            registry: ghcr.io
            repository: belodetek/kubernetes-secret-generator # this image is multi-arch supporting both amd64 and arm64.
            tag: 0.0.4
      - name: minio-operator
        repo: https://operator.min.io
        remoteChart: operator
        namespace: minio
        createNamespace: true
        wait: true
        version: 7.0.0
      - name: minio-tenant
        repo: https://operator.min.io
        remoteChart: tenant
        namespace: shopware
        createNamespace: true
        wait: true
        version: 6.0.3
        setValues:
          tenant:
            name: minio-shopware
            buckets:
              - name: public
                objectLock: false
                region: local
              - name: private
                objectLock: false
                region: local
            pools:
              - servers: 1
                volumesPerServer: 1
                size: 2Gi
                name: pool0
                securityContext:
                  runAsUser: 1000
                  runAsGroup: 1000
                  fsGroup: 1000
                  fsGroupChangePolicy: "OnRootMismatch"
                  runAsNonRoot: true
                containerSecurityContext:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  seccompProfile:
                    type: RuntimeDefault
      - name: cert-manager
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        repo: https://charts.jetstack.io
        version: v1.15.3
        wait: true
        setValues:
          installCRDs: true
          ingressShim:
            defaultIssuerKind: ClusterIssuer
            defaultIssuerName: selfsigned
      - name: sealed-secrets
        remoteChart: sealed-secrets
        namespace: sealed-secrets
        createNamespace: true
        repo: https://bitnami-labs.github.io/sealed-secrets
        version: 2.16.1
        wait: true
verify:
  - name: e2e
    container:
        name: e2e
        image: kiweeteam/shopware-e2e
        env:
          - name: CI
            value: true
        command:
          - /bin/sh
        args:
          - -c
          - |
            set -e
            echo "Waiting until the homepage is accessible..."
            curl -kILSs --fail --retry 10 --retry-all-errors http://shopware.test/
            echo "GitHub summary = ${GITHUB_STEP_SUMMARY}"
            echo "Running E2E tests..."
            npx playwright test
            echo "GitHub summary = ${GITHUB_STEP_SUMMARY}"
            echo "E2E tests finished."
    executionMode:
      kubernetesCluster:
        jobManifestPath: deploy/overlays/dev/app/e2e.yaml
