apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    app: shopware
    component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-shopware
  selector:
    app: shopware
    component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    app: shopware
    component: web
spec:
  selector:
    matchLabels:
      app: shopware
      component: web
  replicas: 3
  template:
    metadata:
      labels:
        app: shopware
        component: web
    spec:
      securityContext:
        fsGroup: 33
      containers:
        - name: app-server
          args:
            - php-server
            - -l
            - 0.0.0.0:8000
            - -a
            - -v
            - --no-compress
          image: kiweeteam/franken-shopware
          envFrom:
            - configMapRef:
                name: shopware-app-config
            - secretRef:
                name: shopware-app-config
            - secretRef:
                name: database-credentials
            - secretRef:
                name: shopware-credentials
          env:
            - name: SHOPWARE_ADMINISTRATION_PATH_NAME
              value: "admin_$(SHOPWARE_ADMINISTRATION_PATH_SUFFIX)"
            - name: DATABASE_URL
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: CONSOLE_ACCESS_KEY
                  name: shopware-s3
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: CONSOLE_SECRET_KEY
                  name: shopware-s3
          ports:
            - name: http-shopware
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
            - mountPath: /var/www
              name: homedir
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            runAsNonRoot: true
            readOnlyRootFilesystem: true
      restartPolicy: Always
      volumes:
        - name: tmpdir
          emptyDir:
            sizeLimit: 1Gi
        - name: homedir
          emptyDir:
            sizeLimit: 16Mi
