apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: shopware-s3
spec:
  forceRegenerate: false
  fields:
    - fieldName: "CONSOLE_ACCESS_KEY"
      encoding: "base64"
      length: "32"
    - fieldName: "CONSOLE_SECRET_KEY"
      encoding: "base64"
      length: "48"
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    meta.helm.sh/release-name: minio-tenant
    meta.helm.sh/release-namespace: shopware
  labels:
    app: minio
  name: minio-shopware
spec:
  buckets:
    - name: public
      objectLock: false
      region: local
    - name: private
      objectLock: false
      region: local
  configuration:
    name: myminio-env-configuration
  features:
    bucketDNS: false
    enableSFTP: false
  image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      name: pool0
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      volumesPerServer: 1
  prometheusOperator: false
  requestAutoCert: true
  subPath: /data
  users:
    - name: shopware-s3

